#!/usr/bin/env python3

import time
import colors as c
print(c.clear)

for count in range(4):

    for count in range(12):
    print('badgers')
    time.sleep(0.4)

    for count in range(2):
    print('mushrooms')
    time.sleep(0.8)

print(c.clear)
print(snake)
