#!/usr/bin/env python3

import colors as c
import random

dice = [ ]

dice.append('''
 -------
|       |
|   o   |
|       |
 -------
''')
dice.append('''
 -------
|       |
|   1   |
|       |
 -------
''')
dice.append('''
 -------
|       |
|   2   |
|       |
 -------
''')
dice.append('''
 -------
|       |
|   3   |
|       |
 -------
''')
dice.append('''
 -------
|       |
|   4   |
|       |
 -------
''')
dice.append('''
 -------
|       |
|   5   |
|       |
 -------
''')
dice.append('''
 -------
|       |
|   6   |
|       |
 -------
''')

while True:
    die = random.choice(dice)
    print(c.clear + c.random_color() + die + c.reset)
    input()
