#!/usr/bin/env python3


import colors as c
import time

G = c.green
Y = c.yellow
R = c.red

print('multiply multiply multiply')
number = input('multiply multiply multiply?')
print('table for {}:'.format(number))

for multiplier in range(12,0,-1):
    answer = multiplier * int(number)
    print (G + str(multiplier) + Y + 'x' + number, end=' = ' + R)
    print('{} x {} = {}'.format(number,multiplier,answer))
