#!/usr/bin/env python3

import time
import colors as c

hundreds = 0
seconds = 0
minutes = 0

print('control-c to stop')

while True:
    time.sleep(.01)
    print(c.clear)
    print(c.green + 'control-c to stop' + c.reset)
    print(minutes)
    print(seconds)
    print(hundreds)
    hundreds += 1
    if hundreds == 100:
        seconds += 1
        hundreds = 0
    if seconds == 60:
        minutes += 1
        seconds = 0
